server:
  servlet:
    context-path: /robot

moli:
  api:
    key: 76937134966920eec5cfb8f5510e3653
    secret: ny2b2ox2z7ml
  qa:
    url: http://i.itpk.cn/api.php

tencent:
  appId: 2121016897
  appKey: CuzRL6BtyzG9HMxv
  qa:
    url: https://api.ai.qq.com/fcgi-bin/nlp/nlp_textchat
